name: GitHub Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity
          plugin_traffic: yes
          plugin_languages: yes
          plugin_code: true
          plugin_achievements: yes
