name: GitHub Metrics
on:
   workflow_dispatch:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity
          plugin_contributions: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_languages: yes
          plugin_code: yes

